### ISSUE TITLE
Violent shutdown

### ISSUE THREAD

**Issue by Kerl13** [Kerl13/GHA#11]
Hi,

Is there actually a way to shutdown the bot silently ? I usually type `ctrl+C` to stop the service which raises a lot of errors.

Thank you in advance,
Kerl

**Comment by Niols** [comment]
Hey,

If I remember correctly, you have `--write-pid` option that write all threads pids into a file.
That isn't really less violent, but that might be more convenient:

```
cat file | xargs kill
```

I believe GHA would need to be fully rewritten, but I don't have the motivation to do so...

If this answer is satisfactory, please mark the issue as closed.
Otherwise, and if you have an idea that would solve your problem, don't hesitate to tell (or even to suggest a PR).

Regards,

## 

Niols
